### ISSUE TITLE
Suggested plot: basic stats

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#10]
Can you create a new plot (or set of plots) that has:

- A histogram of the widths of the GRanges object.
- A histogram of the distances between each element in the GRanges object.

Need a name for this kind of plot.

**Comment by tdanehy** [comment]
Notes from meeting:
GRanges is an R representation of a BED file
elements vary in length of base pairs
use width(query) for length, then use ggplot2 to plot a hist of those widths 
as always, will need one function that calculates and one that plots

**Comment by tdanehy** [comment]
Notes from meeting Oct24:

Need to think of different scenarios for the data.
      What if they are all the same length?
      What if they are normally distributed? Exponential?

Might need one strategy for wide variation and one strategy for normal variation

Could create artificial bins with log distribution (that way they are still interpretable)

Another idea: Cascading bins- different levels of bins that collapse as tally increases so there are always 6 showing 

Look into histogram research- variable width histograms. Or better ways to display (like a density plot? boxplot?)
Good article here : https://www.circonus.com/2018/05/effective-management-of-high-volume-numeric-data-with-histograms/

Could remove but note outliers

Final conclusion:
Show middle 80 percent of the data as an evenly spaced histogram, then have 10/90 pct for the last two bins
Define quantiles as bins 
Do what he did on the package feature-plots 
     use function called cut 
     with the last bin being anything "+"

**Comment by nsheff** [comment]
@tdanehy are you coming to the hackathon?

**Comment by nsheff** [comment]
both these plots now exist (once @joseverdezoto finishes the distance one)
