### ISSUE TITLE
warning in cumulative partitions distribution calculation

### ISSUE THREAD

**Issue by joseverdezoto** [databio/GenomicDistributions#100]
The following warning comes up in the vignette when calculating the cumulative partitions distribution. It's pretty verbose so this might be an issue for larger files. 

```
cp2 = calcCumulativePartitionsRef(queryList, "hg19")
```

```
## Warning in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, : Item 2 has 0 rows but longest item has 1; filled with NA
## Warning in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, : Item 3 has 0 rows but longest item has 1; filled with NA
## Warning in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, : Item 2 has 0 rows but longest item has 1; filled with NA
## Warning in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, : Item 3 has 0 rows but longest item has 1; filled with NA
## Warning in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, : Item 2 has 0 rows but longest item has 1; filled with NA
## Warning in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, : Item 3 has 0 rows but longest item has 1; filled with NA
## Warning in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, : Item 2 has 0 rows but longest item has 1; filled with NA
## Warning in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, : Item 3 has 0 rows but longest item has 1; filled with NA
## Warning in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, : Item 2 has 0 rows but longest item has 1; filled with NA
```

**Comment by joseverdezoto** [comment]
@jpsmith5 I was looking at the vignette and found something odd. In the previous release of GenomicDistributions, the cumulative partition distribution calculation for the `query` file yielded a value of 0.62 for intergenic. However, now it's showing an NA value and warnings instead. I wonder if this has to do with the addition of the other partitions

**Comment by nsheff** [comment]
![image](https://user-images.githubusercontent.com/5271009/82045952-f8f36300-967d-11ea-8cbe-36366187cc15.png)

Yes, it looks like something has broken with these plots.

**Comment by joseverdezoto** [comment]
I think I was able to track the bug. I believe it was related to the definition of the intergenic overlaps. This is what it looks like now:
![cumul_part_fixed](https://user-images.githubusercontent.com/24950132/82097538-17367e80-96d1-11ea-8a33-8a640a82ffe6.png)

**Comment by joseverdezoto** [comment]
NAs still appear when I plot different files than the vignette though
