### ISSUE TITLE
WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versio

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#103]
I get this warning now when I build.

>    NB: this package now depends on R (>= 3.5.0)                                                                                  
>     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'GenomicDistributions/data/geneModels_hg19.rda'  WARNING: Added dependency on R >= 3.5.
0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'GenomicDistributions/data/setB_100.rda'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'GenomicDistributions/data/vistaEnhancers.rda'

**Comment by nsheff** [comment]
I guess we have 2 choices:

1. just add a dependency on R >= 3.5.0
2. stop using 'serialize/load version 3' (whatever that is)

thoughts?

**Comment by stolarczyk** [comment]
I don't know what this message is saying either. I'd introduce the dependency, >3.5.0 is low
