### ISSUE TITLE
Partition priority: UTR priorities too low

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#104]
The defaults data puts the UTRs after genes and exons in priority. This means that the only things that would get put into a UTR would have to be 100% contained in the UTR annotation. This effectively means nothing (or very very little) will ever overlap the UTRs, like this:

![image](https://user-images.githubusercontent.com/5271009/82052940-7d4be300-968a-11ea-8635-441de3b81e0d.png)

Instead, the UTRs need to have a higher priority.

**Comment by kkupkova** [comment]
Do you think I should put them even before promoters??

**Comment by kkupkova** [comment]
I kept them after promoters. I am getting UTRs in the partition counts now.

**Comment by nsheff** [comment]
ok looks better now.
