### ISSUE TITLE
.requireAndReturn function missing

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#105]
```
> gc2 = calcGCContentRef(queryList, "hg38")
Error in .requireAndReturn(databasePkgString) : 
  could not find function ".requireAndReturn"
```

was this function removed for some reason? I guess it still builds because these are not used anywhere in the tiny vignette, but in the long vignette I'm now getting errors.

**Comment by stolarczyk** [comment]
I moved it to GenomicDistributionsData, along with the functions from loadData.R but then realized that some are explicitly used by GD code so I left them here. But did not bring the `. requireAndReturn` back.
