### ISSUE TITLE
 could not find function "dtToGR"

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#106]
devtools::check("~/code/GenomicDistributions")

```
❯ checking examples ... ERROR
  Running examples in ‘GenomicDistributions-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: dtToGrInternal
  > ### Title: Two utility functions for converting data.tables into GRanges
  > ###   objects
  > ### Aliases: dtToGrInternal
  > 
  > ### ** Examples
  > 
  > genes = dtToGR(gModels, "chr", "txStart", "txEnd", "strand", "geneId")
  Error in dtToGR(gModels, "chr", "txStart", "txEnd", "strand", "geneId") : 
    could not find function "dtToGR"
  Execution halted
```

was this function removed?

**Comment by stolarczyk** [comment]
it's not being exported

**Comment by joseverdezoto** [comment]
I'm getting the same error when I run the R CMD check. Are utility functions supposed to be exported though?

**Comment by nsheff** [comment]
they have to be if they're used in the examples. we have to either export this, or not use it in an example.


I actually see the problem; someone wrote `dtToGR` instead of `dtToGr`.

**Comment by nsheff** [comment]
This is the problem

https://github.com/databio/GenomicDistributions/blob/e55ff1038cb4f47abb878feaed7aa843e2ed4550/R/utility.R#L77

and actually there are more problems there, since `gModels` is not found. So, this wasn't really tested I guess

**Comment by nsheff** [comment]
> ### Name: labelCuts
> ### Title: Creates labels based on a discretization definition.
> ### Aliases: labelCuts
> 
> ### ** Examples
> 
> labelCuts(seq(0,100,by=20))
Error in labelCuts(seq(0, 100, by = 20)) : 
  could not find function "labelCuts"
Loading GenomicDistributions

Not sure what happened here but now there appear to be multiple examples that are broken.

**Comment by nsheff** [comment]
Ok I think someone added roxygen-style examples to several unexported functions. I've just taken them out. we can't have examples on unexported functions, because those functions can't be called.

I can now run examples successfully.
