### ISSUE TITLE
BiocCheck missing fixes

### ISSUE THREAD

**Issue by joseverdezoto** [databio/GenomicDistributions#110]
@nsheff  I fixed what I could yesterday, but we still have 1 error, 1 warning and 6 notes. This error seems a bit problematic since we defined non-runnable examples for the below functions.
```
* Checking exported objects have runnable examples...
    * ERROR: At least 80% of man pages documenting exported objects must have runnable examples. The following pages do not:
      binBSGenome.Rd, calcChromBins.Rd, calcGCContent.Rd, calcGCContentRef.Rd, calcOpenSignal.Rd, loadBSgenome.Rd, loadEnsDb.Rd, plotOpenSignal.Rd
```
I'm not really sure how to interpret this warning:
```
* Checking individual file sizes...
    * WARNING: The following files are over 5MB in size: '.git/objects/pack/pack-ca1cb4ce46e91ea538b69b6ea1fde3960930240e.pack'
```
Lastly, there are few notes regarding code style. Given that it's not mandatory to fix these issues, do you think we should do it anyways? It might take a bit to go through all of them.
```
$note
[1] "Avoid sapply(); use vapply() found in files:"                                                                                                                                     
[2] " Avoid 1:...; use seq_len() or seq_along() found in files:"                                                                                                                       
[3] "Consider shorter lines; 154 lines (3%) are > 80 characters long."                                                                                                                 
[4] "Consider 4 spaces instead of tabs; 328 lines (7%) contain tabs."                                                                                                                  
[5] "Consider multiples of 4 spaces for line indents, 323 lines(7%) are not."                                                                                                          
[6] "Cannot determine whether maintainer is subscribed to the bioc-devel mailing list (requires admin credentials).  Subscribe here:\nhttps://stat.ethz.ch/mailman/listinfo/bioc-devel"
```

**Comment by nsheff** [comment]
> Given that it's not mandatory to fix these issues

what do you mean? why is it not mandatory?

**Comment by nsheff** [comment]
Ok I tried adding `.git` to `.Rbuildignore`, see if that solves the file size problem.

**Comment by joseverdezoto** [comment]
Ok I see. I was just wondering because the `BiocCheck` website says the following about notes:
```
NOTE: Not necessarily something bad, just something we wanted to point out. package authors don’t need to take action on these, but they can.
```

**Comment by nsheff** [comment]
Oh I see. They should be easy to fix though. Maybe dont' have to get 100% of everything, but a lot of it should be fixable.

**Comment by joseverdezoto** [comment]
> Ok I tried adding `.git` to `.Rbuildignore`, see if that solves the file size problem.

I'm still getting the file size warning:
```
* Checking individual file sizes...
    * WARNING: The following files are over 5MB in size: '.git/objects/pack/pack-ca1cb4ce46e91ea538b69b6ea1fde3960930240e.pack'
```

**Comment by joseverdezoto** [comment]
> Oh I see. They should be easy to fix though. Maybe dont' have to get 100% of everything, but a lot of it should be fixable.

Ok, I'll start going trough those. I think fixing the examples error is priority though.

**Comment by nsheff** [comment]
Hi @joseverdezoto are the Bioc updates ready to go?

**Comment by joseverdezoto** [comment]
I haven’t been able to fix the warning about the file size. Once we get that done, and I push some changes, we should be good to go. There were almost 200 lines longer than 80 characters so I’m working on that now.

**Comment by nsheff** [comment]
the .git warning doesn't make sense to me at all. why are .git files being included in the build tarball?

**Comment by joseverdezoto** [comment]
I’m not sure either. The BiocCheck function takes the package directory as input so maybe there’s an argument to ignore git files?

**Comment by nsheff** [comment]
oh, that's why. that's not how you should do it;  First you build it with:  `R CMD build ...`. then you check the result of that with: `R CMD BiocCheck`. don't run check on the folder before building.

**Comment by joseverdezoto** [comment]
Oh I see. I’ll try again once I go through the remaining lines.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joseverdezoto** [comment]
I'm trying to run the R CMD BiocCheck, but I'm getting the following error:
```
Checking for support site registration...
Error in if (suppressMessages(content(response))) { : 
  argument is not interpretable as logical
```
I checked and this doesn't seem to come from GenomicDistributions. Have you found this issue before?

**Comment by nsheff** [comment]
> Have you found this issue before?

nope.

**Comment by joseverdezoto** [comment]
I think this is the problem (check for support site registration and not the package itself)
```
Response [https://support.bioconductor.org/static/message.txt]
  Date: 2020-05-21 17:15
  Status: 200
  Content-Type: text/plain
  Size: 253 B
#
# Your IP has made too many requests to the site.
#
# Access from your IP has been limited for a period of time.
#
# Visit the main site and try again later.
```

**Comment by joseverdezoto** [comment]
@nsheff I'm no longer getting `ERRORS` or `WARNINGS`. I fixed what I could regarding `NOTES`.

Summary:
ERROR count: 0
WARNING count: 0
NOTE count: 5

**Comment by nsheff** [comment]
Ok, just ran it through after re-building vignettes... I see: 

* Checking package size...                                                                                                         
    * ERROR: Package Source tarball exceeds Bioconductor size                                                                      
      requirement.                                                                                                                 
        Package Size: 5.5433 MB                                                                                                    
        Size Requirement: 5.0000 MB


and: 

* Checking function lengths.................................................
    * NOTE: Recommended function length <= 50 lines.
      There are 9 functions > 50 lines.
      The longest 5 functions are:
        plotOpenSignal() (R/specificity-plots.R, line 116): 146 lines
        plotFeatureDist() (R/feature-plots.R, line 167): 92 lines 
        plotCumulativePartitions() (R/partition-plots.R, line 437): 82
      lines
        calcOLCount() (R/aggregate.R, line 24): 76 lines
        calcCumulativePartitions() (R/partition-plots.R, line 319): 72
      lines

**Comment by nsheff** [comment]
I'm trying to merge the full power and data vignettes to cut down on space.

**Comment by nsheff** [comment]
Ok, got it down to 4.5 Mb
