### ISSUE TITLE
plotOpenSignal suggestions

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#113]
I have 2 suggestions for plot open signal

1. function length:

     * NOTE: Recommended function length <= 50 lines.
      There are 9 functions > 50 lines.
      The longest 5 functions are:
        plotOpenSignal() (R/specificity-plots.R, line 116): 146 lines

2. compute time. It seems there are some computations going on int his function, because it takes a long time to plot. can we get all the compute-heavy calculations out of the plot function into the calc function?

**Comment by kkupkova** [comment]
2: All calculations are now done in calc function.

**Comment by nsheff** [comment]
is the note addressed?

**Comment by kkupkova** [comment]
> is the note addressed?

2. is addressed. 
1. is not addressed. I actually made even the first function longer. I can separate that into signal matrix function and stats function. But I don't know, what could I do about the plotting function - should I make a different function for different type of plot? So there would be a function for bar plot, for jitter plot, etc. I kind of wanted to avoid that and just use the type of the plot as an option in the plotting function.

**Comment by nsheff** [comment]
they can just be internal functions if you want. so the user interface stays the same. 

this is not for the user at all, it's for the developer -- if you have really long functions it's sometimes hard to get your head around what you're doing in the function. I don't have strong feelings about it. 150 lines isn't terrible. but this is the suggestion so it might be worth at least considering whether it makes sense to split those up, which could be a good idea. Otherwise this note will come up every time anyone runs check.
