### ISSUE TITLE
Bioconductor submission status

### ISSUE THREAD

**Issue by joseverdezoto** [databio/GenomicDistributions#114]
@nsheff The issue for the package submission has been created. This is the Bioconductor [build report](http://bioconductor.org/spb_reports/GenomicDistributions_buildreport_20200525124211.html) received so far. There are currently 1 `ERROR` and 1 `WARNING`.
- [x] `ERROR` comes from changing the package version from 0.8 to 0.99.z 
- [x]  `WARNING` comes from updating the R dependency from 3.5 to 4.0. Should we update this dependency or keep it as it is?

Also, we need to add [webhook](https://github.com/Bioconductor/Contributions/blob/master/CONTRIBUTING.md#adding-a-web-hook) to the repository. I don't think I can do it since I don't have access to the repository settings menu.

**Comment by nsheff** [comment]
FYI, I had updated the version in https://github.com/databio/GenomicDistributions/commit/cc42e07262fcabbd5335c0dbe760292e710d30a4

> Should we update this dependency or keep it as it is?

Update it. I don't like this one but I they will require it.

**Comment by nsheff** [comment]
> Also, we need to add webhook to the repository. I don't think I can do it since I don't have access to the repository settings menu.

I've granted you permission.

**Comment by joseverdezoto** [comment]
> FYI, I had updated the version in [cc42e07](https://github.com/databio/GenomicDistributions/commit/cc42e07262fcabbd5335c0dbe760292e710d30a4)
> 
> > Should we update this dependency or keep it as it is?
> 
> Update it. I don't like this one but I they will require it.

Oh I assumed the main branch was up to date with `dev`. I just saw the version change in `dev`. Should we merge those changes  into master?

**Comment by joseverdezoto** [comment]
I'll update the R dependency in `dev` and then merge into master

**Comment by joseverdezoto** [comment]
UPDATE:  latest [build report] (http://bioconductor.org/spb_reports/GenomicDistributions_buildreport_20200526113047.html) from Bioc bot. Package was built without `ERRORS` or `WARNINGS`

**Comment by nsheff** [comment]
@joseverdezoto is this completed?
