### ISSUE TITLE
Is there GenomicDistributions compatibility with R 3.6?

### ISSUE THREAD

**Issue by hugokitano** [databio/GenomicDistributions#116]
I'm on a cluster that only has R 3.6, without many permissions to change this. Installing with devtools right now gives me an error. Thanks!

Hugo Kitano

**Comment by nsheff** [comment]
Hugo, would you mind pasting the exact error you get? Thanks

**Comment by hugokitano** [comment]
Sorry about that, here it is 
![image](https://user-images.githubusercontent.com/8139124/86955319-3ae3d700-c10c-11ea-8956-467a269cb0ae.png)

**Comment by hugokitano** [comment]
Hi Nathan, just checking back in with this, is there a way to get GenomicDistributions to work with R 3.6? Thank you!

Hugo

**Comment by nsheff** [comment]
yeah, this is a pain, sorry. It's because biocondutor requires you to set that. it's not really that the package requires it, it's that it belongs to the next version of bioconductor.  try this:

```R
devtools::install_github("databio/GenomicDistributions",  ref="r3.6")
```

**Comment by hugokitano** [comment]
thanks!
