### ISSUE TITLE
update install instructions

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#122]
[REQUIRED] L45-47 Once your package is submitted to Bioconductor it should
    be installed as follows.

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("GenomicDistributions")

Please add this and remove the github_install() instructions.

**Comment by kkupkova** [comment]
Should I update it just in README and in vignettes later? I don't think I would be able to build vignettes at this point.
