### ISSUE TITLE
Help with Sorting using nbins 

### ISSUE THREAD

**Issue by ser9gj** [databio/GenomicDistributions#129]
Earlier I sorted the graph based on the df$cut string:

```
if (labelOrder == "TSS"){
        temp = df[df$cuts == "0 to 2,000",]
        orderedLabels = temp[order(temp$Freq, decreasing = TRUE), ]$name
        orderedNames = factor(df$name, levels = orderedLabels)
        return(orderedNames)
```

The issue with that is that the default number of nbins has to be used. I want to base it on the frequency of the middle nbins value (nbins + 1-- there are nbins on each side of the TSS midpoint) for each of the groups (vistaEnhancers, shifted). 

How can I avoid using a loop but still index at nbins + 1 intervals?

**Comment by kkupkova** [comment]
Hi! You can alway use indexing. You just have to know, how many bins you generate, then create a vector of positions of middle bins and use that for indexing. I think you don't need a for loop for that. If you know, that the number of bins is 50, then the TSS should be bin 25, and the next one 75, ... The positions are then `seq(round(nbin/2), nbin*bedFiles, by = nbin)`, where `nbin` = number of bins per bed file, `bedFiles` = number of bed files provided.

```
bedFiles = 3
nbin = 50
seq(round(nbin/2), nbin*bedFiles, by = nbin)
[1]  25  75 125
```

**Comment by ser9gj** [comment]
Thank you!

**Comment by ser9gj** [comment]
The only thing is that when I use the example with more than two bed files, it cuts off after 7. It ends up looking like this...
<img width="563" alt="Screen Shot 2021-02-28 at 10 40 44 AM" src="https://user-images.githubusercontent.com/62667360/109424416-86a40300-79b1-11eb-9e25-12b88ab01bd4.png">
