### ISSUE TITLE
Relative partition distributions

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#17]
In [Sheffield et al. 2018](https://doi.org/10.1038/nm.4273), Figure S9f and S9g, I produced some "relative" partition distributions. They are similar to the partition distribution plots produced by GenomicDistributions, but provide log ratios of partitions relative to background, instead of absolute counts. We should implement this as an additional plot type in GenomicDistributions.

**Comment by nsheff** [comment]
@jpsmith5 you have done this for the peppro here:

http://peppro.databio.org/en/dev/files/examples/paper/reports/prif.html

**Comment by jpsmith5** [comment]
Gotcha, will include that plot as well. Heads up, that link took me to a 2015 paper with supplemental figures only up to S5?

**Comment by nsheff** [comment]
fixed the link

**Comment by jpsmith5** [comment]
Completed.
