### ISSUE TITLE
Distance to TSSs is wrong

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#173]
In BEDbase, distance calculations to TSS are still incorrect.

Noticed by @Khoroshevskyi

**Comment by kkupkova** [comment]
Can you give an example, where it's wrong, since our previous test datasets passed?

**Comment by nsheff** [comment]
@Khoroshevskyi can you follow up?

**Comment by Khoroshevskyi** [comment]
I am in contact with Kristyna. It looks like distance to TSS values are correct. Absolute distances TSS are huge values. If values are the same after second check we will close the issue.

**Comment by Khoroshevskyi** [comment]
@nsheff @kkupkova . I tryed to calculate mean absolute distance to TSS with rGREAT. Results are similar but not the same (I have checked with different options: oneClosest, twoClosest... ) If you are sure that results are correct, than we can close this issue.

**Comment by nsheff** [comment]
Ok I have investigated this in depth now. I think you are right that the calculation is (roughly) correct. The issue is that the distribution of distances to TSS is similar to an exponential distribution with a very long tail. We have been taking the mean of this distribution, which is not a good indicator of the distribution because it is greatly skewed by outliers.

I will close this issue and re-raise in bedstat.
