### ISSUE TITLE
Confusion about branches

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#177]
I'm making changes on my dev branch and pushing them and I'm getting this warning:

```
remote: 
remote: Heads up! The branch 'dev' that you pushed to was renamed to 'release_0_99_4'.
```

I am confused by this. I have always developed on a dev branch, and I don't really understand what's going on. I have not experienced this before so I don't really know what I'm expected to do.

I'm definitely not intending to push to a release branch, I'm just making dev changes. So, how did my dev branch get renamed to `release_...` ?

**Comment by kkupkova** [comment]
This might be my mistake - I was creating a release branch from dev branch (I guess I renamed it and then created a new branch called dev). I will make sure it does not happen again, but the current dev branch on GitHub is a true dev branch - you might just need delete your local dev branch and clone this one again.
