### ISSUE TITLE
Tissue specificity plots

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#18]
I made [a function](https://github.com/databio/RGenomeUtils/blob/2475368f58f1a0c0d40f57d9d37aae32b7355256/R/funcLoadSharedData.R#L173-L185) that evaluates tissue specificity, using DNAse data. 

Following the GenomicDistributions approach of dividing calc from plot functions; 

- `calcTissueSpecificity`: Given a GRanges object, I return some matrix of tissue specificity
- `plotTissueSpecificity`: returns a ggplot object of the result.

**Comment by kkupkova** [comment]
The location of the cell specific open signal matrices in Rivanna: /sfs/qumulo/qproject/shefflab/processed/open_chromatin_matrix
