### ISSUE TITLE
Feature distance distribution plots, switch to percentage

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#20]
If you have a grangeslist that has granges objects with widely different numbers of elements, the distributions aren't comparable because the scale-y is not free.

**Comment by stolarczyk** [comment]
can't use `facet_grid` with freed scales, that's `ggplot2` design decision: https://github.com/tidyverse/ggplot2/issues/1152

but it works when we switch to `facet_wrap`

![grid](https://user-images.githubusercontent.com/22797900/77547537-b4b8c300-6e83-11ea-8ba4-f639768a5cf5.png)
![wrap](https://user-images.githubusercontent.com/22797900/77547559-baaea400-6e83-11ea-829e-1cd5b47b780d.png)

**Comment by stolarczyk** [comment]
will use percentage of regions instead of number of regions and the first layout

**Comment by stolarczyk** [comment]
![new](https://user-images.githubusercontent.com/22797900/77570948-ec833300-6ea2-11ea-9e67-9b9bdaa454de.png)
