### ISSUE TITLE
Custom partitions for a custom reference

### ISSUE THREAD

**Issue by rrashford** [databio/GenomicDistributions#206]
Hello!

I am using the mm39 genome (which I would have to make a custom reference for), but would like to include enhancers to my partitions list. When I'm creating my custom reference gene models, would I include "enhancers" just as I include $gene and $exon? Or would I have to follow the code for "[Custom features (partitions)](https://www.bioconductor.org/packages/release/bioc/vignettes/GenomicDistributions/inst/doc/intro.html#custom-features-partitions)" to add to my newly made custom reference (mm39)?

Please let me know if the question isn't clear!
Best,

**Comment by kkupkova** [comment]
Hi! 

You would have to follow the instructions in "[Custom features (partitions)](https://www.bioconductor.org/packages/release/bioc/vignettes/GenomicDistributions/inst/doc/intro.html#custom-features-partitions)" section. 

Let me explain why. You will be creating gene models from GTF file. GTF file does not contain the information about enhancers. So what you do is you first create a partition list consisting of features that can be found in the GTF file. The instructions can be found here: [Gene models](https://www.bioconductor.org/packages/release/bioc/vignettes/GenomicDistributions/inst/doc/intro.html#gene-models). 

In this step you create GRangesList (named partitionList here) that has information from your GTF file. What you want to do next is to append GenomicRanges object with your enhancer coordinates to this list. If you have a BED file with the enhancer coordinates all you need to do is: 

```
enhancers = rtracklayer::import("path/to/BED/file/with/enahncers")
partitionList[["enhancer"]] = enhancers
```

I hope this is understandable, please let me know if anything needs clarification or if you run into issues!

Best,
Kristyna

**Comment by rrashford** [comment]
Thank you! This makes sense. However, I don't have a BED file of enhancer coordinates from mm39. If this is the case, could I follow the Custom features (partitions) section to get all of the predicted enhancers, convert them into a GRanges object, then add them to my partitionList object?

Below is my code for creating my custom reference and attempting to add mm39 enhancers. I'm unsure if this approach would get me to the correct set of enhancers (mm39 predicted enhancers as opposed to hg19 or mm10 predicted enhancers)? If this makes sense, would it be correct to use this approach?

`fastaSource = "https://ftp.ensembl.org/pub/release-108/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna_sm.toplevel.fa.gz"`

`gtfSource = "https://ftp.ensembl.org/pub/release-108/gtf/mus_musculus/Mus_musculus.GRCm39.108.gtf.gz"`

### step 1: get chromosome sizes
`mm39ChromSizes = getChromSizesFromFasta(source=fastaSource)
bins = getGenomeBins(mm39ChromSizes)`

### step 2: transcription start sites
`mm39TSSs = getTssFromGTF(source=gtfSource, convertEnsemblUCSC=TRUE)`

### step 3: gene models for partition plots
`features = c("gene", "exon", "intron", "three_prime_utr", "five_prime_utr")`
`mm39GeneModels = getGeneModelsFromGTF(source=gtfSource, features=features, convertEnsemblUCSC=TRUE)`

`partitionList = genomePartitionList(mm39GeneModels$gene, 
                                    mm39GeneModels$exon,
                                    mm39GeneModels$intron,
                                    mm39GeneModels$three_prime_utr, 
                                    mm39GeneModels$five_prime_utr)`

### getting predicted enhancers from Ensembl
`funcgen = biomaRt::useMart("ENSEMBL_MART_FUNCGEN", host="https://useast.ensembl.org/")`
`funcgen = biomaRt::useDataset("mmusculus_regulatory_feature", mart=funcgen)`

`enhancers = biomaRt::getBM(attributes=c('chromosome_name',
                                        'chromosome_start',
                                        'chromosome_end',
                                        'feature_type_name'),
                           filters='regulatory_feature_type_name',
                           values='Enhancer',
                           mart=funcgen)`
`enhancers$chromosome_name = paste("chr", enhancers$chromosome_name, sep="")`

`partitionList[["enhancer"]] = enhancers`

Thank you so much!
Best,

**Comment by kkupkova** [comment]
This is correct! I went to ensembl mm39 and double checked that the predicted enhancers are in fact for mm39 and the coordinates match. So you should be good to proceed with your analysis. And again, please reach out if you run into any issues or something isn't clear from the vignette.

Best,
Kristyna
