### ISSUE TITLE
Error installing GenomicDistributionsData

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#208]
When running `BiocManager:install("GenomicDistributionsData")` I get:

```
Error: package or namespace load failed for 'GenomicDistributionsData':
 .onLoad failed in loadNamespace() for 'GenomicDistributionsData', details:
  call: (function (cond) 
  error: error in evaluating the argument 'x' in selecting a method for function 'query': Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/nsheff/R/x86_64-pc-linux-gnu-library/4.2/GenomicDistributionsData’

```

**Comment by kkupkova** [comment]
This is strange, I don't get this error when I install the package. But I found multiple people reporting the same issue (and even recently after the ExperimentHub incident in October):

https://stackoverflow.com/questions/77370659/error-failed-to-collect-lazy-table-caused-by-error-in-db-collect-using
https://support.bioconductor.org/p/9154865/

Could this have something to do with your `dbplyr` version?

**Comment by nsheff** [comment]
No, I re-installed that, and I updated all my packages... I'm still getting the same error...

**Comment by nsheff** [comment]
I was able to solve the problem by updating to the latest version of R (from 4.2 to 4.3) and bioconductor. I'm not sure what it is but there must have been some incompatibility in some previous version, but updating everything all around and the problem went away.
