### ISSUE TITLE
More comprehensive unit tests

### ISSUE THREAD

**Issue by j-lawson** [databio/GenomicDistributions#21]
There are only a few unit tests. Make unit tests for functions that calculate things.

- [x] calcOpenSignal() from openRegionsCalcAndPlot.R
- [x] calcGCContent() from content-plots.R

From chrom-plots.R:
- [x] binRegion(). Might have unit tests for this in MIRA or COCOA. 
- [x] calcChromBins()

- [x] BSAggregate from aggregate.R. Definitely made unit tests for this in MIRA/COCOA.

From partition-plots.R:
- [x] calcPartitions
~- [ ] partitionPercents?~

j-lawson currently working on
- [x] DTNearest
- [x] calcFeatureDist

**Comment by nsheff** [comment]
@j-lawson can you repurpose your tests for the aggregate function?

**Comment by j-lawson** [comment]
Yeah I'll work on the test for the aggregation.

**Comment by j-lawson** [comment]
I'm adding the test for BSAggregate to test_all.R

**Comment by nsheff** [comment]
is this done?

**Comment by j-lawson** [comment]
I found a potential bug in the calcChromBins function due to BSAggregate. Can you talk on Zoom? @nsheff

**Comment by nsheff** [comment]
yes

**Comment by j-lawson** [comment]
I'm going to replace BSAggregate with a much shorter and simpler function since it is only being used to count overlaps

**Comment by nsheff** [comment]
sounds great!

**Comment by nsheff** [comment]
I believe this has been completed.
