### ISSUE TITLE
Input checks

### ISSUE THREAD

**Issue by j-lawson** [databio/GenomicDistributions#23]
Check that correct input class is given. Give warning/error. If possible convert to correct type.

**Comment by nsheff** [comment]
```
if !class(query) %in% c("GRanges", "GRangesList") {
 //
}
```

**Comment by nsheff** [comment]
@stolarczyk says we can use `setGeneric()` ?

**Comment by j-lawson** [comment]
I was thinking of something like "checkConvertInputClasses()" function in COCOA. Using "is()" is BIOC recommended instead of class() %in% ...

**Comment by nsheff** [comment]
Closing in favor of #28
