### ISSUE TITLE
chrombins plot orientation error

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#25]
has anyone else seen this problem in the chrombins plot?

it is plotting the orientation wrongly...
![chrombins](https://user-images.githubusercontent.com/5271009/77539290-8339fa80-6e77-11ea-8ad5-0a3ebebbf03e.png)

**Comment by joseverdezoto** [comment]
yeah, I just came across that issue. It also happens when you plot the 2 queries. This didn't happen when I ran the vignette a few months ago. It's odd because when I use `bedstat` I get the right plots.

**Comment by nsheff** [comment]
fix:

```
		# scale_y_discrete(breaks=c(0, max(genomeAggregate$N)), limits=c(max(genomeAggregate$N))) + 
		scale_y_continuous(breaks=c(max(genomeAggregate$N)), limits=c(0, max(genomeAggregate$N))) +
```
