### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by j-lawson** [databio/GenomicDistributions#26]
Not all exported functions have "@return" describing the output. For "@param" and "@return", it would be good at the least to have the class of object that is input/output. This can come right at the beginning of the line. Example for plotChromBins() function: @param genomeAggregate The output from the genomicDistribution function => change to => @param genomeAggregate X-class object. The output from the genomicDistribution function.

**Comment by nsheff** [comment]
Should probably go through again after changes are made.
