### ISSUE TITLE
Error in calcPartitions

### ISSUE THREAD

**Issue by stolarczyk** [databio/GenomicDistributions#41]
This used to be possible:
http://code.databio.org/GenomicDistributions/articles/intro.html#partition-distribution-plots

now: 
```
> queryFile = system.file("extdata", "vistaEnhancers.bed.gz", package="GenomicDistributions")
> query = rtracklayer::import(queryFile)
> calcPartitionsRef(query, "hg19")
Error in calcPartitions(query, partitionList) : 
  partitionList should be a GRanges list. Check object class.
```

@joseverdezoto is the class check the culprit here?

**Comment by joseverdezoto** [comment]
Yeah, that is coming from the class checks. Not sure why since the argument `partitionList` should be a `GRangesList`.

**Comment by joseverdezoto** [comment]
Oh I think I found the issue. It should be a list, not a GRangesList

**Comment by joseverdezoto** [comment]
@stolarczyk I just pushed the fix to `calcPartitions`. Let me know if you have other issues

**Comment by stolarczyk** [comment]
where did you push it? it's still failing on dev

**Comment by stolarczyk** [comment]
oh, to your branch, I'll merge it

**Comment by joseverdezoto** [comment]
I pushed it to `dev` but I haven't made a pull request

**Comment by stolarczyk** [comment]
worked!
