### ISSUE TITLE
Error: Failed to install 'GenomicDistributions' from GitHub

### ISSUE THREAD

**Issue by qiaowei-vvjoe** [databio/GenomicDistributions#5]
Hi 
I am now install GenomicDistributions R package in R-3.5 but there is an error I cannot fix it.

Installing package into '/mnt/disk1/qiaowei/R/x86_64-pc-linux-gnu-library/3.5'
(as 'lib' is unspecified)
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error: Failed to install 'GenomicDistributions' from GitHub:
  (converted from warning) installation of package '/tmp/RtmpH6y9vQ/file11f9b5e4b71c6/GenomicDistributions_0.6.tar.gz' had non-zero exit status

I guess if the error [non-zero exit] caused by the  LC_CTYPE, because change LC_CTYPE need root privileges.And I haven't the privileges.
Thanks so much in advance.

**Comment by nsheff** [comment]
are you sure this is a problem with genomic distributions? It seems like a problem with your R or environment or something... I don't do anything with LC_CTYPE in this package. I'm not sure what this error actually means but maybe this helps:

https://stackoverflow.com/questions/27299420/how-to-get-rid-of-warning-messages-after-installing-r/28163310

**Comment by qiaowei-vvjoe** [comment]
@nsheff 
hi 
yes.The LC_CTYPE is something about my terminal in MAC which language is English.Just now when I try to install this package in my macbook which language is Chinese,it succeed.Thank you so much for your quick reply.
