### ISSUE TITLE
missing data in package

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#55]
```
> file_list = c("UTR3.bedGraph.gz", "UTR5.bedGraph.gz",
+               "Enhancer.bedGraph.gz", "Exon.bedGraph.gz",
+               "Intron.bedGraph.gz", "Promoter.bedGraph.gz",
+               "Promoter_Flanking.bedGraph.gz")
> loadFunction = function(file) {
+     queryFile = system.file("extdata", file, package="GenomicDistributions")
+     query = rtracklayer::import.bedGraph(queryFile)
+     names(elementMetadata(query)) <- "count"
+     return(query)
+ }
> query = lapply(file_list, loadFunction)
```

Error in connectionForResource(manager, resource, open = "r") : 
  path cannot be an empty string

Did you forget to put these into the package?
Also, didn't I already have these in the package? yes -- I have already put the geneModels into /data for partition plots.

is this just old? the vignette won't run

**Comment by nsheff** [comment]
I'm really confused by what you're doing here. maybe we can just talk about it?

**Comment by jpsmith5** [comment]
Ah. The data files were in the git ignore. So I thought I had included them but did not force their inclusion.  Adding to dev now.

**Comment by jpsmith5** [comment]
What geneModels are you referencing? These are data coverage files.

**Comment by nsheff** [comment]
> What geneModels are you referencing? 

https://github.com/databio/GenomicDistributions/tree/master/data

**Comment by nsheff** [comment]
look at the partition plots. the whole point is that these are a corrected version of the partition plots, but it seems you aren't even aware that this exists:

https://github.com/databio/GenomicDistributions/blob/master/R/partition-plots.R

**Comment by jpsmith5** [comment]
So are those annotation files? In this case, these are not annotation files. Right. I'm aware of those plots, which are different than what I have here.

**Comment by jpsmith5** [comment]
I think those stand separate, as my data is dependent exclusively on the annotation files that generated the input data. Which are coverage files, not annotation files.

**Comment by jpsmith5** [comment]
THe input to these functions are the results of performing coverage calculations on independent feature/annotation files.

**Comment by jpsmith5** [comment]
The input to the plotPartitions functions are a set of regions right?

**Comment by nsheff** [comment]
I believe this was solved, please reopen if I'm wrong
