### ISSUE TITLE
Data source for included reference data

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#57]
GD relies on some reference data. This data falls into 2 categories 1) small-ish data that can be included in the package (gene models, chromsizes, tss); 2) large data that can't be included in the package (tissue specificity matrix, bsgenome objects).

Even for class 1 (small data), we can't include it for every genome. The functions are flexible and can take user-provided ref data in both cases.

Would it make sense to transition to refgenie for one or both of these reference data categories? If so, would we want some R interface to refgenie to do that? or would we introduce a requirement for reticulate? Would we want this requirement to be optional, so we would still include the data but just *allow* using refgenie?

**Comment by nsheff** [comment]
the gene models are actually about 1 mb per genome, and causing the package to raise a NOTE on CMD check...

**Comment by nsheff** [comment]
Hey @stolarczyk -- this is pretty cool:

```
install.packages('reticulate')
rgcmodule = reticulate::import("refgenconf", convert=FALSE)
rgc = rgcmodule$RefGenConf("/home/nsheff/pCloudSync/env/refgenie_config/zither.yaml")
rgc$seek("hg38", "fasta")
```

It's pretty seamless to use refgenie from R in fact.

**Comment by stolarczyk** [comment]
oh I didn't know reticulate makes it _this_ straightforward!

Looking at this code snippet it would not make sense to write an R wrapper for refgenie, then. We could just document it well.
