### ISSUE TITLE
Finish partition percentage plots

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#58]
Related to #17 

There are incomplete partition percentage plots

they also use 'tableCount', which needs to be addressed (see #56)
https://github.com/databio/GenomicDistributions/blob/f73259470339919cdb755ae2e775a3f87b76cbdb/R/partition-plots.R#L140

**Comment by nsheff** [comment]
Similar concept to #20 for a different plot type.

**Comment by joseverdezoto** [comment]
So far this is what the plot looks like with 1 region
![part_percent_1region](https://user-images.githubusercontent.com/24950132/81188648-961a1180-8f83-11ea-9067-85491f74d857.png)

**Comment by nsheff** [comment]
looks great
