### ISSUE TITLE
Ideas for visualizing clustering of regions in set

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#61]
- are these 'flat' (non-overlapping)?
- what is the degree of non-flatness?
- do these cluster? compare the feature-to-feature distance distribution vs. a random set of similar size

for each of these plots would be interesting to see where my region set lies on a range, with marked:
- 'random' 
- 'enhancers' 
- 'promoters

**Comment by joseverdezoto** [comment]
We discussed if it'd be better to plot the distances as QT histogram. I think there's some value to plot the log transformed distances because it's easier to see how the distribution within a regionset compares to that of another file. If we plot the actual distances as a histogram, it's harder to draw that distinction. Or maybe we could offer the option of plotting any of the 2 alternatives?

![neighboring_dists_prelim](https://user-images.githubusercontent.com/24950132/80622855-5ef1b080-8a17-11ea-8e54-fc97bfe74ef6.png)

**Comment by joseverdezoto** [comment]
@nsheff do you think the plot looks ok? I want to make the appropriate changes before I push it. It needs to be documented too.

**Comment by nsheff** [comment]
I don't follow your argument...why does the log space make it more easy to compare? In normal space, the difference here would be off the charts. I guess my opinion is that it should not be in log space. But, I haven't looked at enough data, so I don't really now. 

What you show here seems reasonable enough, even if I am skeptical of the log transformation.

**Comment by kkupkova** [comment]
In cell type specificity plot add enrichment over background.

**Comment by nsheff** [comment]
Here's a demonstration of a QThist for the same data in this log density plot. Which do you find easier to interpret?

![image](https://user-images.githubusercontent.com/5271009/115768663-99ff9900-a378-11eb-948c-659ea049da62.png)
![image](https://user-images.githubusercontent.com/5271009/115768692-a4219780-a378-11eb-99fe-e1b7cc7bbbb9.png)

code:

```
nd = calcNeighborDist(query)
plotQTHist(10^nd, quantile=.05)
plotNeighborDist(nd)
```

**Comment by nsheff** [comment]
@joseverdezoto what do you want to do here?

**Comment by nsheff** [comment]
@joseverdezoto can you update on the status of this issue please?

**Comment by joseverdezoto** [comment]
Updated functions for calculating raw/corrected distances between regions and distance to nearest neighbors have been added to my branch. I'll merge that into dev.

**Comment by nsheff** [comment]
ok that's a good idea!

**Comment by nsheff** [comment]
In the vignette posted in the docs, the scale is still the old way.

code.databio.org/GenomicDistributions/articles/intro.html

**Comment by joseverdezoto** [comment]
Just fixed a bug in the intro vignette and rendered with the latest changes. Not sure how to add it to the code.databio.org webpage though

**Comment by kkupkova** [comment]
I'll do it with the new release. Is the bug also in the long vignette?

**Comment by joseverdezoto** [comment]
Ok cool. Nop, the bug is not present in the long vignette. Just the intro vignette since it was using the `quantile` arg that was recently removed.

**Comment by kkupkova** [comment]
Ah, awesome, thanks for catching that.
