### ISSUE TITLE
extremely verbose function output

### ISSUE THREAD

**Issue by stolarczyk** [databio/GenomicDistributions#70]
As shown in [this log](https://github.com/databio/GenomicDistributions/files/4499924/bedstat_log.txt), one of the functions in this package produces tens of thousands of warnings

It is _probably_ a result of the line below, but need to double check.

https://github.com/databio/GenomicDistributions/blob/757b74e1ff61abbbe175e02545b806ca2de715e1/R/content-plots.R#L75

**Comment by joseverdezoto** [comment]
Fixed in the `dev_jose` branch.
