### ISSUE TITLE
Reducing data footprint of package

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#75]
R CMD check gives this NOTE:

```
* checking installed package size ... NOTE
  installed size is  9.4Mb
  sub-directories of 1Mb or more:
    data   6.9Mb
    doc    2.3Mb
```

Can we reduce the size of the data included?

**Comment by nsheff** [comment]
Related to #57

**Comment by jpsmith5** [comment]
For additional clarification, from Bioconductor:
- The source package resulting from running R CMD build should occupy less than 5MB on disk.
- The package should require less than 10 minutes to run R CMD check --no-build-vignettes.
- Vignette and man page examples should not use more than 3GB of memory.
- For software packages, individual files must be <= 5MB.

**Comment by nsheff** [comment]
we will need smaller versions of these data files like gene models still included int he packages for the vignettes and example tests.

**Comment by nsheff** [comment]
another idea: we could remove the geneModels and TSS for hg19, mm9, and mm10, but leave them for hg38, and then use those for the examples.

That will get us under 5MB.

**Comment by stolarczyk** [comment]
ok, that works.

Also, I'm planning to make every example dataset an `.rda` file, so that we don't have any in `inst/extdata`. The datasets will be ready to use once the package is loaded. The BED files would become `GRanges` objects. 
Is there any value in keeping the raw ones? Do we care about showcasing BED files reading in every example?

**Comment by nsheff** [comment]
I guess the value is just that we can show in the vignettes how to start from a bed gz file. probably not necessary for every example, but do you think that's helpful at least for one example? if so you can't get completely rid of them...

**Comment by nsheff** [comment]
Do you mind keeping the data objects named `.RData` instead of `.rda` (unless there is some reason to change?)

**Comment by stolarczyk** [comment]
I don't have preference, as far as I know these are interchangable. 

I switched to `.rda` in GenomicDistributions and GenomicDistributionsData because the function I used for creation of the objects (`usethis::use_data()`) uses this extension.

Is there any reason you want them back in `.RData`?

**Comment by nsheff** [comment]
I think the functions I had written to load them in expected `.RData` objects, so the package was kind of built around that. we could change the functions, too, I guess...I have a slight preference for `.RData` because I know immediately what it is, while `.rda` could be anything... not a strong feeling

**Comment by stolarczyk** [comment]
The functions used to create the datasets specify extensions. The functions _reading_ the data unaware of the extensions. However they have to be rewritten anyway, because now, for example, they need to look for `geneModels_mm10` in GenomicDistributionsData since it's no longer included in GenomicDistributions. I'm starting to work on that. 

I'll keep the format change in mind. I'll focus on getting the whole system to work for now.

**Comment by nsheff** [comment]
Ok, related side note, we now are down to:

```
* checking installed package size ... NOTE
  installed size is  5.1Mb
  sub-directories of 1Mb or more:
    data   1.8Mb
    doc    3.0Mb
```

**Comment by nsheff** [comment]
Looks like thats the *installed* size -- our source file is only 3.2 Mb. The 5bm limit is actually for source tarballs, so looks like we're OK.

**Comment by nsheff** [comment]
Oh yeah, about this:

> Also, I'm planning to make every example dataset an .rda file, so that we don't have any in inst/extdata. The datasets will be ready to use once the package is loaded. The BED files would become GRanges objects. Is there any value in keeping the raw ones? Do we care about showcasing BED files reading in every example?

From here: http://r-pkgs.had.co.nz/data.html#data-extdata

Data for vignettes. If you want to show how to work with an already loaded dataset, put that data in data/. If you want to show how to load raw data, put that data in inst/extdata.

Does moving it to *data* mean we're required to document it? I'm not sure if  this is related to this error I'm getting in R check:

```
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  ‘cellTypeMetadata’ ‘exampleOpenSignalMatrix_hg19’
Undocumented data sets:
  ‘cellTypeMetadata’ ‘exampleOpenSignalMatrix_hg19’
```

**Comment by stolarczyk** [comment]
> Does moving it to data mean we're required to document it?

yes, and `exampleOpenSignalMatrix_hg19` is documented here, but I just noticed that `@name` is wrong. The `cellTypeMetadata` is yet to be documented

https://github.com/databio/GenomicDistributions/blob/cab086cd24898991a903fc61157c04832bdcebb7/R/data.R#L30-L48

**Comment by nsheff** [comment]
Here's the tarball for GenomicDistributionsData:
http://big.databio.org/GenomicDistributionsData/

Where do you keep the actual pre-build source?

**Comment by stolarczyk** [comment]
I didn’t create the source, I just used the tarball for installation. I’ll create it and place it next to the tarball.

**Comment by stolarczyk** [comment]
GenomicDistributionsData is now available either at http://big.databio.org/GenomicDistributionsData/GenomicDistributionsData_0.0.1.tar.gz
as a tarball (installable with `install.packages()`) or in the repository: https://github.com/databio/GenomicDistributionsData.
