### ISSUE TITLE
handling narrow widths distribution in plotQThist

### ISSUE THREAD

**Issue by joseverdezoto** [databio/GenomicDistributions#76]
If there's not a wide enough distribution of widths in a regionSet, `plotQThist` produces the following error:

``` 
Error in cut.default(dists, divisions, labels) : 'breaks' are not unique 

5.stop("'breaks' are not unique") 
4.cut.default(dists, divisions, labels) 
3.cut(dists, divisions, labels) 
2.cutDists(widths, divisions = output[["divisions"]]) 
1.plotQTHist(demo_widths)
```

**Comment by kkupkova** [comment]
This is now fixed. 
Another problem is that if I have 2 widths, e.g. 10 x 10 bp,  20 x 11 bp in the dataset, I will get following intervals:  10 x (<10) / 20x (10-11) / 0x (>11) ... it should be 0 x (<10) / 30x (10-11) / 0x (>11)

**Comment by nsheff** [comment]
well... it's just a question of openness of the intervals, right? is it:
```
[-Inf, 10)
[10, 11)
[11, Inf)
```

or:
```
(-Inf, 10]
(10, 11]
(11, Inf]
```
Isn't that it? maybe we just need to change the `<` to be `<=` ?
