### ISSUE TITLE
Names of vignette chunks for images

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#81]
@jpsmith5 Can you look into the formatting for vignette chunks? I noticed that some of the images you added don't have legends on them:

![image](https://user-images.githubusercontent.com/5271009/81289625-b81f9c80-9034-11ea-8588-2f7047815871.png)

See how the legend shows up in the first image, but no legend in the second one? It's because of spaces in the first argument of the vignette chunk. I wanted to point this out to you for future reference

**Comment by jpsmith5** [comment]
Ah, alright. Am I editing the vignette to fix this or did you already change it?

**Comment by nsheff** [comment]
I haven't changed it
