### ISSUE TITLE
GC content multi-plot questions

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#88]
![image](https://user-images.githubusercontent.com/5271009/81339205-c7760880-907b-11ea-814a-2c7d81554de3.png)

there are 2 things I don't understand about this plot:

1. there are 4 region sets here; why is there only 1 curve? Given that the medians look different,  the sets can't have  exactly the same gc content distribution
2. why is the region set color using a gradient scale? it is a discrete value

**Comment by nsheff** [comment]
@joseverdezoto forgot to bring this up, but can you comment on this?

**Comment by joseverdezoto** [comment]
Oh I know why. That happens if you don't provide a named `GRangesList`. When you melt the data, the name of each regionset  is required to color the different density curves. That's how the `queryList` in the vignette is formatted.

**Comment by joseverdezoto** [comment]
Just tested it
![gc_multiple](https://user-images.githubusercontent.com/24950132/81345469-89caad00-9086-11ea-9666-8da873fae077.png)

**Comment by joseverdezoto** [comment]
Tested more than 2 regionsets just in case:

![gc_plot_multitest](https://user-images.githubusercontent.com/24950132/81434501-3adb5100-9134-11ea-898f-16be6d50a2f0.png)
