### ISSUE TITLE
Rbuild ignore data-raw?

### ISSUE THREAD

**Issue by nsheff** [databio/GenomicDistributions#94]
Should data-raw be added to .Rbuildignore ? Otherwise you get:

```
Non-standard files/directories found at top level:
     ‘data-raw’
```

**Comment by stolarczyk** [comment]
yes it should 

> Often, the data you include in data/ is a cleaned up version of raw data you’ve gathered from elsewhere. I highly recommend taking the time to include the code used to do this in the source version of your package. This will make it easy for you to update or reproduce your version of the data. I suggest that you put this code in data-raw/. You don’t need it in the bundled version of your package, so also add it to .Rbuildignore
